### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by lxxself** [VaalaCat/vorker#1]
使用docker-compose.yml构建
打开控制页面后注册成功，但登录的时候，尽管显示了登录成功，但页面依然有登录按钮，且日志提示如下
```
06/06/2023 2:46:29 PM
time="2023-06-06T06:46:29Z" level=error msg="Not Authed"
06/06/2023 2:46:29 PM
time="2023-06-06T06:46:29Z" level=error msg="Not Authed"
06/06/2023 2:46:40 PM
time="2023-06-06T06:46:40Z" level=error msg="Not Authed"
```

**Comment by VaalaCat** [comment]
可以在浏览器打开f12看看network栏里的login请求返回是什么

**Comment by lxxself** [comment]
> 可以在浏览器打开f12看看network栏里的login请求返回是什么，重点看看header里的cookie domian和返回是否为OK

![image](https://github.com/VaalaCat/vorker/assets/8406766/39674606-64a3-48b9-9822-2c559fb566d9)
请问是哪里出问题了？

**Comment by lxxself** [comment]
还是一样，当前我的配置是这样
```
version: '3'

services:
  vorker:
    image: vaalacat/vorker
    volumes:
      - ./workerd:/workerd
      - ./workerd-linux-64:/bin/workerd
    environment:
      - DB_PATH=/workerd/db.sqlite
      - WORKERD_DIR=/workerd
      - WORKERD_BIN_PATH=/bin/workerd
      - DB_TYPE=sqlite
      - WORKER_LIMIT=10000
      - WORKER_PORT=8080
      - API_PORT=8888
      - LISTEN_ADDR=0.0.0.0
      - WORKER_DOMAIN_SUFFIX="worker.com" # worker url = SCHEME://WORKERNAME+WORKER_DOMAIN_SUFFIX
      - SCHEME=http
      - ENABLE_REGISTER=false # only allow admin to register
      - COOKIE_NAME=authorization
      - COOKIE_AGE=21600 # sec
      - COOKIE_DOMAIN=192.168.3.100
      - JWT_SECRET=123123
      - JWT_EXPIRETIME=6 # hour
    ports:
      - 8001:8080
      - 8002:8888
    restart: unless-stopped
```
